development:
  adapter: postgresql
  encoding: utf8
  database: mark1_development
  host: localhost
  pool: 5
  timeout: 5000
  username: calvin
  password: password

test:
  adapter: postgresql
  encoding: utf8
  database: mark1_test
  pool: 5
  timeout: 5000
  username: calvin
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: mark1_production
  pool: 5
  timeout: 5000
  username: calvin
  password: password
