# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa496356740e81c7358ee37a17222995a955d8c0c4e7816eab2c8035131da6bacd5ed1b0de612179b0e59c5926bc1e555463815c617d76df3c354c3be8a227b

test:
  secret_key_base: 28d62564dacac915c5fdbc1e72505e21707c0db9c42e8763c50b4b023d0def08489725cd7908326c8193201a96a8434b0ff7953145b51ceeb5ef64f5425c8bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
